---

- name: Instalación de apache2.
  become: yes
  apt:
     name: apache2

- name: Configuración del virtualhost.
  become: yes
  copy:
    src: etc/apache2/sites-available/drupal.conf
    dest: /etc/apache2/sites-available/
    owner: root
    group: root
    mode: 0644

- name: Activar el virtualhost.
  become: yes
  file:
    src: /etc/apache2/sites-available/drupal.conf
    dest: /etc/apache2/sites-enabled/drupal.conf
    owner: root
    group: root
    mode: 0644
    state: link
  notify: restart apache2
