Vagrant.configure("2") do |config|  
  config.vm.define :ansible do |ansible|
    ansible.vm.box = "debian/stretch64"
    ansible.vm.hostname = "apache"
    ansible.vm.network :private_network, ip: "192.168.0.10"
  end
end

