---

- name: Instalación de postgresql.
  become: yes
  apt:
    name:
      - postgresql-9.6
      - python-psycopg2
    install_recommends: no

- name: Asegurarse que el servicio está corriendo y se iniciará en el próximo reinicio.
  service: name=postgresql state=started enabled=yes

#- name: Cambio de contraseña al usuario postgres.
#  become_user: postgres
#  postgresql_user:
  
#- name: Configuración de la base de datos.

- name: Creación del usuario para drupal.
#  connection: ssh
  vars:
    ansible_ssh_pipelining: true
  become: yes
  become_user: postgres
  postgresql_user:
#    login_user: postgres
#    login_host: 127.0.0.1
    name: drupal
    password: drupal

- name: Creación de la base de datos.
  become_user: postgres
  postgresql_db:
    name: drupal_db
    owner: drupal
