---

- name: Instalación de postgresql.
  become: yes
  apt:
    name:
      - postgresql-9.6
      - python-psycopg2
    install_recommends: no

- name: Asegurarse que el servicio está corriendo y se iniciará en el próximo reinicio.
  become: yes
  service: name=postgresql state=started enabled=yes

- name: Creación del usuario para drupal.
  vars:
    ansible_ssh_pipelining: true
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"

- name: Creación de la base de datos.
  vars:
    ansible_ssh_pipelining: true
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    owner: drupal

- name: Importar la base de datos de drupal.
  become: yes
  copy:
    src: opt/backups/drupal.sql
    dest: /tmp/drupal.sql

- name: Restaurar la base de datos de drupal.
  vars:
    ansible_ssh_pipelining: true
  become: yes
  become_user: postgres
  postgresql_db:
    name: drupal_db
    state: restore
    target: /tmp/drupal.sql

- name: Configurar la bd para que escuche desde cualquier IP.
  become: yes
  shell: echo "listen_address = '*'" >> /etc/postgresql/9.6/main/postgresql.conf

- name: Configuración de la bd para que sea accesible desde nodo2.
  become: yes
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/9.6/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640