---

- name: Actualiza el sistema.
  gather_facts: false
  hosts: all
  roles:
    - role: common

- name: Instala y configura en el nodo 1 los roles correspondientes (dns y bd).
  gather_facts: false
  hosts: nodo1
  roles:
    - role: bind9
    - role: postgresql

### Instala en el nodo 2 los roles correspondientes (servidor web y módulo php).
#- hosts: nodo2
#  roles:
#   - role: apache
#   - role: php
